#define MAX_WEEK 20
#define STARTING_NUM_BELLS 5000
#define STARTING_NUM_TURNIPS 0
#define VICTORY_NUM_BELLS 1000000000
#define TURNIP_STACK_SIZE 10
#define SUNDAY_TURNIP_MIN_PRICE 90 // Daisy Mae's Price
#define SUNDAY_TURNIP_MAX_PRICE 110 // Daisy Mae's Price
#define AVERAGE_TREND_TURNIP_MIN_PRICE 80
#define BAD_TREND_TURNIP_MIN_PRICE 20
