#define MAX_WEEK 20
#define STARTING_NUM_BELLS 5000
#define VICTORY_NUM_BELLS 1000000000
#define TURNIP_STACK_SIZE 10
#define DAISY_MAE_TURNIP_MIN_PRICE 90
#define DAISY_MAE_TURNIP_MAX_PRICE 110
#define AVERAGE_TREND_TURNIP_MIN_PRICE 80
#define BAD_TREND_TURNIP_MIN_PRICE 20
